### ISSUE TITLE
Get-a2aPassword doesn't work on Redhat

### ISSUE THREAD

**Issue by aamburn** [OneIdentity/safeguard-bash#36] opened 2021-03-04 20:52 UTC
Output is empty but SPP Activity Center shows successful password retrieval. 

Repro steps: 

Use Get-a2aPassword from Redhat device. Notice empty response.
Log into SPP and navigate to Activity Center. Observe password release event. 
Use Get-a2aPassword from Ubuntu device. Notice response containing password.
Log into SPP and navigate to Activity Center. Observe another password release event.

**Comment by petrsnd** [comment] 2021-03-04 23:08
Near as I can tell, this is caused by the fail over to openssl s_client for client certificate authentication on platforms where curl is linked to gnutls that has bugs.  I don't think the openssl s_client output is being parsed properly.

**Comment by petrsnd** [comment] 2021-03-12 14:09
Fixed in https://github.com/OneIdentity/safeguard-bash/releases/tag/release-6.9.6347 pre-release.

**Closed by petrsnd** 2021-03-12 14:09 UTC
Labels: bug
